import type { Metadata } from 'next';
import { Navbar, Footer } from '@/components/navigation';

export const metadata: Metadata = {
    title: 'GOAT NEWS',
    description: 'Generated by create next app',
};

export default function BaseLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="relative w-full min-h-screen overflow-x-hidden">
            <Navbar />
            <main className="flex-1 max-w-7xl mx-auto px-4">{children}</main>
            <Footer />
        </div>
    );
}
